In [1]:
import pandas as pd
import numpy as np

In [2]:
l = ["abhishek",3,4,3,5,7]

In [3]:
np.array(l)

array(['abhishek', '3', '4', '3', '5', '7'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
a1 = np.array([2,356,7,5,6])


In [8]:
a = np.array([[1,2],[6,4]])

In [9]:
a

array([[1, 2],
       [6, 4]])

In [10]:
a[1][1]

4

In [11]:
a1

array([  2, 356,   7,   5,   6])

In [12]:
a1[4]

6

In [14]:
a2 = np.array([3,4,5,3,5], ndmin =4) # how much dimensions you want

In [15]:
a2

array([[[[3, 4, 5, 3, 5]]]])

In [16]:
a2[0]

array([[[3, 4, 5, 3, 5]]])

In [18]:
a2[0]

array([[[3, 4, 5, 3, 5]]])

In [20]:
a2[0][0][0][0]

3

In [21]:
a

array([[1, 2],
       [6, 4]])

In [22]:
np.asanyarray([345678,2345,67,6543,45]) # function

array([345678,   2345,     67,   6543,     45])

In [24]:
np.asarray([3,4,6,4,6,4]) # function

array([3, 4, 6, 4, 6, 4])

In [25]:
np.mat([2,2,3,5,])

matrix([[2, 2, 3, 5]])

In [27]:
a = [3,3,4,6,87,9,5]
np.mat(a)

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [28]:
np.asarray(a)

array([ 3,  3,  4,  6, 87,  9,  5])

In [29]:
np.mat(a)

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [34]:
np.asanyarray(np.mat(a))

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [35]:
np.asarray(np.mat(a))

array([[ 3,  3,  4,  6, 87,  9,  5]])

In [36]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda  i,j,z,p: i*j*z*p , (4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [39]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [40]:
a.reshape(2,4,-234) # reshape is used to change dimensions

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [42]:
a.reshape(2,4,-1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [43]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [44]:
a.ndim # to get how much dimensions are present

3

In [45]:
a.size # how much element are present

24

In [46]:
a.shape

(4, 3, 2)

In [47]:
a.dtype

dtype('int32')

In [48]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [50]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [51]:
a = np.fromfunction(lambda i, j: i*j, (400,100),dtype=int)

In [52]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [53]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [54]:
np.random.rand(100,4)

array([[0.34170729, 0.43811007, 0.48887876, 0.8248727 ],
       [0.80425051, 0.97970246, 0.46746229, 0.01248774],
       [0.93169252, 0.9114203 , 0.02085854, 0.71548931],
       [0.27624638, 0.91714881, 0.7712582 , 0.33201874],
       [0.3070311 , 0.01139237, 0.55769484, 0.468788  ],
       [0.32335274, 0.94097988, 0.40055287, 0.6643544 ],
       [0.89382475, 0.78357358, 0.48976972, 0.03706581],
       [0.12447998, 0.2509121 , 0.23448164, 0.38041015],
       [0.480434  , 0.27260649, 0.69277497, 0.43474439],
       [0.21379183, 0.85126549, 0.87728979, 0.31355578],
       [0.19805625, 0.57390482, 0.84453706, 0.2871338 ],
       [0.25507984, 0.63134092, 0.43543041, 0.13060896],
       [0.95886785, 0.2734402 , 0.96592663, 0.17169038],
       [0.01919447, 0.63891854, 0.90350624, 0.22771753],
       [0.0129883 , 0.14617282, 0.46720715, 0.86553803],
       [0.6562902 , 0.13137383, 0.06584719, 0.87216689],
       [0.90510952, 0.95695403, 0.8881801 , 0.40989336],
       [0.39147319, 0.20447033,

In [57]:
np.random.randint(4,50) # gives randon between  4 and 50

12

In [58]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.969568 -0.548119  1.194032 -1.030993  1.488315
1 -0.438822  1.429787 -1.720014 -0.841955  1.173847
2 -1.423569  0.190118 -0.256403  1.380047 -1.023635
3  0.207178  1.146926  0.092054 -0.041675  0.091856

In [60]:
list(range(410,5,.2)) # no float values for steps

TypeError: 'float' object cannot be interpreted as an integer

In [62]:
# FLOAT VALUES CAN BE USED  IN NUMPY range function
a1 = np.arange(4,10,.2)

In [63]:
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [64]:
a1[4:10]

array([4.8, 5. , 5.2, 5.4, 5.6, 5.8])

In [65]:
arr = np.random.rand(4,5)

In [66]:
arr

array([[0.52365523, 0.42524489, 0.54704624, 0.18600574, 0.05914884],
       [0.34967174, 0.55833028, 0.21865196, 0.46309257, 0.50765322],
       [0.08469205, 0.73174593, 0.35671237, 0.25985938, 0.93063073],
       [0.60941726, 0.06615489, 0.96682372, 0.25269645, 0.85866697]])

In [67]:
arr[ arr > .5]

array([0.52365523, 0.54704624, 0.55833028, 0.50765322, 0.73174593,
       0.93063073, 0.60941726, 0.96682372, 0.85866697])

In [68]:
arr

array([[0.52365523, 0.42524489, 0.54704624, 0.18600574, 0.05914884],
       [0.34967174, 0.55833028, 0.21865196, 0.46309257, 0.50765322],
       [0.08469205, 0.73174593, 0.35671237, 0.25985938, 0.93063073],
       [0.60941726, 0.06615489, 0.96682372, 0.25269645, 0.85866697]])

In [69]:
arr[[1,2],[2]]

array([0.21865196, 0.35671237])

In [70]:
arr = np.random.rand(8,5)

In [71]:
arr

array([[0.37852674, 0.90128925, 0.75282563, 0.9000214 , 0.39971929],
       [0.71311882, 0.93936727, 0.09104082, 0.49756247, 0.41893977],
       [0.84955447, 0.65600573, 0.46252031, 0.46116034, 0.54910983],
       [0.32794815, 0.64718464, 0.92993337, 0.82026062, 0.03897116],
       [0.47128831, 0.41799221, 0.47274406, 0.02001917, 0.53129498],
       [0.19587587, 0.56285312, 0.21895619, 0.8610599 , 0.4984621 ],
       [0.77641705, 0.58885806, 0.93831709, 0.60367169, 0.99204703],
       [0.5878494 , 0.91543578, 0.12536532, 0.95803844, 0.73882291]])

In [73]:
arr[1:8, 0:3]

array([[0.71311882, 0.93936727, 0.09104082],
       [0.84955447, 0.65600573, 0.46252031],
       [0.32794815, 0.64718464, 0.92993337],
       [0.47128831, 0.41799221, 0.47274406],
       [0.19587587, 0.56285312, 0.21895619],
       [0.77641705, 0.58885806, 0.93831709],
       [0.5878494 , 0.91543578, 0.12536532]])

In [74]:
a2 = arr[1:8, [0,1,2]]

In [75]:
a2

array([[0.71311882, 0.93936727, 0.09104082],
       [0.84955447, 0.65600573, 0.46252031],
       [0.32794815, 0.64718464, 0.92993337],
       [0.47128831, 0.41799221, 0.47274406],
       [0.19587587, 0.56285312, 0.21895619],
       [0.77641705, 0.58885806, 0.93831709],
       [0.5878494 , 0.91543578, 0.12536532]])

In [78]:
a2[0][0] = 100

In [79]:
a2

array([[1.00000000e+02, 9.39367265e-01, 9.10408192e-02],
       [8.49554472e-01, 6.56005734e-01, 4.62520314e-01],
       [3.27948153e-01, 6.47184642e-01, 9.29933371e-01],
       [4.71288311e-01, 4.17992209e-01, 4.72744059e-01],
       [1.95875865e-01, 5.62853120e-01, 2.18956191e-01],
       [7.76417051e-01, 5.88858061e-01, 9.38317090e-01],
       [5.87849395e-01, 9.15435780e-01, 1.25365317e-01]])

In [82]:
a = np.array([[2,4],[45,45]])
b = np.array([[56,4],[35,56]])

In [83]:
a

array([[ 2,  4],
       [45, 45]])

In [84]:
b

array([[56,  4],
       [35, 56]])

In [85]:
a*b # element wise multiplication not matrix mupltiplication

array([[ 112,   16],
       [1575, 2520]])

In [86]:
# for matrix multiplication
m = a@b

In [87]:
m

array([[ 252,  232],
       [4095, 2700]])

In [88]:
m/0 # o/p is inf

C:\Users\Abhishek Sakhare\AppData\Local\Temp\ipykernel_12396\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [5]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [7]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810200e-306, 9.34601642e-307],
       [7.56581472e-307, 1.60218491e-306, 1.42413555e-306,
        1.78019082e-306, 1.37960147e-306],
       [1.33511562e-306, 2.22518251e-306, 1.33511969e-306,
        1.78022342e-306, 1.05700345e-307],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306]])

In [8]:
np.empty((4,5,2))

array([[[ 0.00000000e+000,  6.95290381e-310],
        [ 1.45255300e-321,              nan],
        [ 7.58328320e-302,  2.67674880e-297],
        [ 3.01331943e-282,  2.04560526e-277],
        [ 2.88217829e+002,  2.13451447e-287]],

       [[ 2.78286850e-307,  2.85163880e-210],
        [ 2.13451447e-287,  1.64294084e-287],
        [ 3.01288598e-282,  3.01628619e-282],
        [ 5.11783286e-307, -1.48541028e-065],
        [ 1.54303069e-065, -1.26967865e-277]],

       [[ 2.49499309e-306,  3.38553712e-301],
        [ 4.62706591e-273,  5.11767330e-307],
        [ 1.38774107e-272,  1.38774107e-272],
        [ 1.10830327e-253,  1.39069238e-309],
        [ 1.75380122e-292,  1.07190753e-296]],

       [[ 5.72844698e-263,  4.68710690e-243],
        [ 3.41529431e-291,  1.67548547e-309],
        [ 2.50642605e-292,  1.78438593e-306],
        [ 3.48069273e-308,  2.58046969e-263],
        [ 1.39909626e-309,  1.30082730e-258]]])

In [2]:
np.empty((5,4,2))

array([[[6.95290916e-310, 6.95290916e-310],
        [6.95290916e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [5]:
np.linspace(2,6, 10) # start number and end number it gives number in between them

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [6]:
np.linspace(2,6, 100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [12]:
np.linspace(2,6, 10,endpoint=False).reshape(5,2) # it will not consider number 6

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [14]:
np.linspace(2,6, 10,endpoint=False, retstep=True) # it will not consider number 6

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [16]:
np.logspace(2,4,10, base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [3]:
a = np.arange(16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
a.max()

15

In [6]:
a.min()

0