In [1]:
import pandas as pd
import numpy as np

In [2]:
l = ["abhishek",3,4,3,5,7]

In [3]:
np.array(l)

array(['abhishek', '3', '4', '3', '5', '7'], dtype='<U11')

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
a1 = np.array([2,356,7,5,6])


In [6]:
a = np.array([[1,2],[6,4]])

In [7]:
a

array([[1, 2],
       [6, 4]])

In [8]:
a[1][1]

4

In [9]:
a1

array([  2, 356,   7,   5,   6])

In [10]:
a1[4]

6

In [11]:
a2 = np.array([3,4,5,3,5], ndmin =4) # how much dimensions you want

In [12]:
a2

array([[[[3, 4, 5, 3, 5]]]])

In [13]:
a2[0]

array([[[3, 4, 5, 3, 5]]])

In [14]:
a2[0]

array([[[3, 4, 5, 3, 5]]])

In [15]:
a2[0][0][0][0]

3

In [16]:
a

array([[1, 2],
       [6, 4]])

In [17]:
np.asanyarray([345678,2345,67,6543,45]) # function

array([345678,   2345,     67,   6543,     45])

In [18]:
np.asarray([3,4,6,4,6,4]) # function

array([3, 4, 6, 4, 6, 4])

In [19]:
np.mat([2,2,3,5,])

matrix([[2, 2, 3, 5]])

In [20]:
a = [3,3,4,6,87,9,5]
np.mat(a)

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [21]:
np.asarray(a)

array([ 3,  3,  4,  6, 87,  9,  5])

In [22]:
np.mat(a)

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [23]:
np.asanyarray(np.mat(a))

matrix([[ 3,  3,  4,  6, 87,  9,  5]])

In [24]:
np.asarray(np.mat(a))

array([[ 3,  3,  4,  6, 87,  9,  5]])

In [25]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda  i,j,z,p: i*j*z*p , (4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [27]:
a = np.fromfunction(lambda i , j ,z : i*j*z , (4,3,2),dtype = int)

In [28]:
a.reshape(2,4,-234) # reshape is used to change dimensions

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [29]:
a.reshape(2,4,-1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [30]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [31]:
a.ndim # to get how much dimensions are present

3

In [32]:
a.size # how much element are present

24

In [33]:
a.shape

(4, 3, 2)

In [34]:
a.dtype

dtype('int32')

In [35]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [36]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a = np.fromfunction(lambda i, j: i*j, (400,100),dtype=int)

In [ ]:
a

In [ ]:
pd.DataFrame(a)

In [ ]:
np.random.rand(100,4)

In [ ]:
np.random.randint(4,50) # gives randon between  4 and 50

In [ ]:
pd.DataFrame(np.random.randn(4,5))

In [ ]:
list(range(410,5,.2)) # no float values for steps

In [ ]:
# FLOAT VALUES CAN BE USED  IN NUMPY range function
a1 = np.arange(4,10,.2)

In [ ]:
a1

In [ ]:
a1[4:10]

In [ ]:
arr = np.random.rand(4,5)

In [ ]:
arr

In [ ]:
arr[ arr > .5]

In [ ]:
arr

In [ ]:
arr[[1,2],[2]]

In [ ]:
arr = np.random.rand(8,5)

In [ ]:
arr

In [ ]:
arr[1:8, 0:3]

In [ ]:
a2 = arr[1:8, [0,1,2]]

In [ ]:
a2

In [ ]:
a2[0][0] = 100

In [ ]:
a2

In [ ]:
a = np.array([[2,4],[45,45]])
b = np.array([[56,4],[35,56]])

In [ ]:
a

In [ ]:
b

In [ ]:
a*b # element wise multiplication not matrix mupltiplication

In [ ]:
# for matrix multiplication
m = a@b

In [ ]:
m

In [ ]:
m/0 # o/p is inf

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,4))

In [ ]:
np.zeros((3,4,5))

In [ ]:
np.ones(5)

In [ ]:
np.ones((4,5,6))

In [ ]:
5+np.zeros((3,4))

In [ ]:
np.empty((4,5))

In [ ]:
np.empty((4,5,2))

In [ ]:
np.empty((5,4,2))

In [ ]:
np.linspace(2,6, 10) # start number and end number it gives number in between them

In [ ]:
np.linspace(2,6, 100)

In [ ]:
np.linspace(2,6, 10,endpoint=False).reshape(5,2) # it will not consider number 6

In [ ]:
np.linspace(2,6, 10,endpoint=False, retstep=True) # it will not consider number 6

In [ ]:
np.logspace(2,4,10, base=10)

In [ ]:
a = np.arange(4,40).reshape(3,6,2)

In [ ]:
a

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.max(axis = 1)

In [ ]:
a.max(axis =0 )

In [37]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [38]:
a**3

array([[[  0,   0],
        [  0,   0],
        [  0,   0]],

       [[  0,   0],
        [  0,   1],
        [  0,   8]],

       [[  0,   0],
        [  0,   8],
        [  0,  64]],

       [[  0,   0],
        [  0,  27],
        [  0, 216]]], dtype=int32)

In [39]:
pow(a,3)

array([[[  0,   0],
        [  0,   0],
        [  0,   0]],

       [[  0,   0],
        [  0,   1],
        [  0,   8]],

       [[  0,   0],
        [  0,   8],
        [  0,  64]],

       [[  0,   0],
        [  0,  27],
        [  0, 216]]], dtype=int32)

In [43]:
b = np.array([3,4,4,34,3,34,4,5,6,7,8,8])

In [45]:
b.reshape(3,4)

array([[ 3,  4,  4, 34],
       [ 3, 34,  4,  5],
       [ 6,  7,  8,  8]])

In [46]:
b.T  # transpose

array([ 3,  4,  4, 34,  3, 34,  4,  5,  6,  7,  8,  8])

In [47]:
b

array([ 3,  4,  4, 34,  3, 34,  4,  5,  6,  7,  8,  8])

In [48]:
b+10

array([13, 14, 14, 44, 13, 44, 14, 15, 16, 17, 18, 18])

In [49]:
a = np.array([3,4,4,34,53,34,84,5,56,57,58,45])

In [50]:
a+b

array([ 6,  8,  8, 68, 56, 68, 88, 10, 62, 64, 66, 53])

In [51]:
np.sqrt(b)  # to get square root

array([1.73205081, 2.        , 2.        , 5.83095189, 1.73205081,
       5.83095189, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 2.82842712])

In [52]:
np.log10(a)

array([0.47712125, 0.60205999, 0.60205999, 1.53147892, 1.72427587,
       1.53147892, 1.92427929, 0.69897   , 1.74818803, 1.75587486,
       1.76342799, 1.65321251])

In [53]:
x = np.array([2,3,4])

In [54]:
y = x

In [56]:
id(x)

2427328516336

In [57]:
id(y)

2427328516336

In [58]:
z = np.copy(x) # deep copy

In [59]:
z

array([2, 3, 4])

In [62]:
k = x  #shallow copy

In [63]:
k

array([2, 3, 4])

In [64]:
k[0] = 44

In [65]:
x

array([44,  3,  4])